# Generated by Django 3.2.6 on 2021-09-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
