# Generated by Django 3.2.6 on 2021-09-19 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210918_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likepost', to=settings.AUTH_USER_MODEL),
        ),
    ]
