# Generated by Django 3.2.6 on 2021-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
